"""Parity tests: two baselines, one delta contract (WORKPLAN T-M0-1 + T-M0-2).

fixtures/legacy/ is the IMMUTABLE monolith baseline: MANIFEST.json records
its sha256 set and capture provenance, the manifest ITSELF is pinned here by
a hardcoded sha256 (EXPECTED_MANIFEST_SHA256), and TestBaselineImmutability
fails if either is edited. A legitimate rebaseline therefore requires
editing this test file, which makes it a visible, reviewable act.

fixtures/corrected/ is the pinned CURRENT behavior (regenerated by
fixtures/capture_corrected.py at each intentional fix): the live package
must reproduce it BYTE-for-byte here. DeltaManifestEnforcement then closes
the loop against legacy/: the observed legacy-vs-corrected diff must equal,
occurrence by occurrence (file, JSON pointer, change kind, exact values on
both sides), the pins hand-committed in fixtures/delta-manifest.json, and
each pinned field carries a written reason. An unintended behavior change
therefore fails twice: against the corrected bytes, and, if corrected/ were
quietly regenerated to hide it, against the value pins in the manifest
(which only a deliberate, reviewed manifest edit can move).
"""
from __future__ import annotations

import hashlib
import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import geopandas as gpd

from scripts.landscape import core
from scripts.landscape.adapters import terrain
from scripts.landscape.tests.fixtures.seams import FIXED_DATE, SENTINEL_SHA256

FIXTURES = Path(__file__).resolve().parent / "fixtures"
SYNTH = FIXTURES / "synthetic"
LEGACY = FIXTURES / "legacy"
CORRECTED = FIXTURES / "corrected"
DELTA_MANIFEST = FIXTURES / "delta-manifest.json"


def load_fixture_gdf() -> gpd.GeoDataFrame:
    return gpd.read_file(SYNTH / "ecoregions_l3.gpkg", layer="ecoregions")


# The trust anchor for the frozen baseline: the manifest's own sha256 and
# the commit the legacy monolith was captured from, pinned in TEST SOURCE.
# Editing the baseline requires editing this file; that is the point.
EXPECTED_MANIFEST_SHA256 = (
    "4b7d3472b093e00d5799e41c78a5418a1e4a91a0a18692e002eb21475137f0ab"
)
EXPECTED_CAPTURE_COMMIT = "2f0f8413365c837690ecb5d849698caec30d6b4f"


class TestBaselineImmutability(unittest.TestCase):
    def test_manifest_itself_is_pinned(self) -> None:
        got = hashlib.sha256((LEGACY / "MANIFEST.json").read_bytes()).hexdigest()
        self.assertEqual(got, EXPECTED_MANIFEST_SHA256,
                         "legacy/MANIFEST.json differs from the pinned hash; "
                         "a rebaseline must be a deliberate, reviewed edit "
                         "of this test")

    def test_capture_commit_is_the_approved_base(self) -> None:
        manifest = json.loads((LEGACY / "MANIFEST.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["capturedFromCommit"], EXPECTED_CAPTURE_COMMIT)

    def test_legacy_baseline_matches_manifest_hashes(self) -> None:
        manifest = json.loads((LEGACY / "MANIFEST.json").read_text(encoding="utf-8"))
        for rel, want in manifest["sha256"].items():
            got = hashlib.sha256((FIXTURES / rel).read_bytes()).hexdigest()
            self.assertEqual(got, want, f"{rel} differs from the frozen baseline")

    def test_corrected_baseline_matches_its_manifest_hashes(self) -> None:
        manifest = json.loads(
            (CORRECTED / "MANIFEST.json").read_text(encoding="utf-8"))
        for rel, want in manifest["sha256"].items():
            got = hashlib.sha256((FIXTURES / rel).read_bytes()).hexdigest()
            self.assertEqual(got, want,
                             f"{rel} differs from its capture manifest; "
                             "regenerate corrected/ via capture_corrected.py")


class TerrainAggregateParity(unittest.TestCase):
    def test_terrain_aggregate_matches_corrected_bytes(self) -> None:
        gdf = load_fixture_gdf()
        with tempfile.TemporaryDirectory() as tmp:
            result = terrain.aggregate(
                gdf,
                "US_L3CODE",
                dem_path=str(SYNTH / "dem.tif"),
                cache_dir=Path(tmp),
            )
        got = (json.dumps(result, indent=2) + "\n").encode("utf-8")
        want = (CORRECTED / "terrain_l3.json").read_bytes()
        self.assertEqual(got, want)

    def test_duplicate_code_is_last_write_wins(self) -> None:
        """The legacy per-feature aggregation overwrites duplicate zonal
        codes; the fixture pins it (code '1' appears twice). This defect is
        DELIBERATELY still preserved after T-M0-2 (the dissolve fix is a
        later unit's scope), so the future fix must be a visible diff."""
        gdf = load_fixture_gdf()
        dupes = gdf[gdf["US_L3CODE"] == "1"]
        self.assertEqual(len(dupes), 2)
        with tempfile.TemporaryDirectory() as tmp:
            result = terrain.aggregate(
                gdf, "US_L3CODE",
                dem_path=str(SYNTH / "dem.tif"), cache_dir=Path(tmp),
            )
            second_only = terrain.aggregate(
                gdf.iloc[[1]], "US_L3CODE",
                dem_path=str(SYNTH / "dem.tif"), cache_dir=Path(tmp),
            )
        self.assertEqual(result["1"], second_only["1"])


def _leaf_diffs(a, b, path: str, out: list[dict]) -> None:
    """Collect every difference between two parsed JSON trees as a record
    {pointer, change, legacy?, corrected?} with a full JSON pointer."""
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            p = f"{path}/{k}"
            if k not in a:
                out.append({"pointer": p, "change": "added", "corrected": b[k]})
            elif k not in b:
                out.append({"pointer": p, "change": "removed", "legacy": a[k]})
            else:
                _leaf_diffs(a[k], b[k], p, out)
        return
    if a != b:
        out.append({"pointer": path, "change": "value", "legacy": a,
                    "corrected": b})


class DeltaManifestEnforcement(unittest.TestCase):
    """legacy/ vs corrected/ may differ ONLY as the delta manifest's
    occurrence pins say, checked per file, per JSON pointer, per change
    kind, and per exact legacy/corrected VALUE, in both directions. A
    quietly regenerated corrected/ with a wrong value at an already-known
    pointer therefore fails against the hand-committed pins here; only a
    deliberate, reviewed manifest edit can move the expectation."""

    FILES = ("terrain_l3.json", "snapshot_terrain_l3.json")

    def _observed(self, name: str) -> list[dict]:
        legacy = json.loads((LEGACY / name).read_text(encoding="utf-8"))
        corrected = json.loads((CORRECTED / name).read_text(encoding="utf-8"))
        out: list[dict] = []
        _leaf_diffs(legacy, corrected, "", out)
        return out

    def _manifest(self) -> dict:
        return json.loads(DELTA_MANIFEST.read_text(encoding="utf-8"))

    @staticmethod
    def _canon(records: list[dict]) -> list[str]:
        return sorted(json.dumps(
            {k: r.get(k) for k in ("pointer", "change", "legacy", "corrected")},
            sort_keys=True) for r in records)

    def test_observed_diff_equals_the_pinned_occurrences_exactly(self) -> None:
        """Both directions at once: an undeclared difference (any file, any
        pointer, any wrong value on either side) and a pinned occurrence
        that no longer holds are both failures."""
        manifest = self._manifest()
        for name in self.FILES:
            with self.subTest(file=name):
                self.assertEqual(
                    self._canon(self._observed(name)),
                    self._canon(manifest["occurrences"][name]),
                    f"the legacy-vs-corrected diff of {name} does not "
                    "match delta-manifest.json's pinned occurrences "
                    "(an unintended behavior change, or a fix missing "
                    "its manifest pin)")

    def test_manifest_files_cover_all_compared_fixtures(self) -> None:
        self.assertEqual(set(self._manifest()["occurrences"].keys()),
                         set(self.FILES))

    def test_every_occurrence_has_an_intent_entry(self) -> None:
        """Each pinned occurrence's terminal field must be explained by
        exactly one fields entry whose declared change KIND matches the
        occurrence's kind, and every fields entry must have at least one
        occurrence (no vacuous intent, no duplicate intents, no intent
        record whose kind misdescribes what actually happened)."""
        manifest = self._manifest()
        fields = [entry["field"] for entry in manifest["fields"]]
        self.assertEqual(len(fields), len(set(fields)),
                         "duplicate field entries in the manifest's intent "
                         "list")
        intent = {entry["field"]: entry["change"]
                  for entry in manifest["fields"]}
        seen: set[str] = set()
        for name in self.FILES:
            for occ in manifest["occurrences"][name]:
                terminal = occ["pointer"].rsplit("/", 1)[-1]
                self.assertIn(terminal, intent,
                              f"occurrence {occ['pointer']} has no intent "
                              "entry in the manifest's fields list")
                self.assertEqual(
                    occ["change"], intent[terminal],
                    f"occurrence {occ['pointer']} is '{occ['change']}' but "
                    f"the intent entry for {terminal} declares "
                    f"'{intent[terminal]}'")
                seen.add(terminal)
        self.assertEqual(set(intent) - seen, set(),
                         "manifest fields entries with no occurrence")

    def test_every_intent_entry_carries_a_reason(self) -> None:
        for entry in self._manifest()["fields"]:
            self.assertTrue(entry.get("reason", "").strip(),
                            f"manifest entry {entry.get('field')} has no reason")
            self.assertIn(entry.get("change"), ("value", "added", "removed"))


class SnapshotParity(unittest.TestCase):
    def _run_main(self, tmp: str, argv: list[str], env: dict | None = None):
        gdf = load_fixture_gdf()
        out_path = Path(tmp) / "snapshot.json"
        patches = [
            mock.patch.object(core, "load_ecoregions", lambda level: gdf),
            mock.patch.object(terrain, "DEM_VRT", str(SYNTH / "dem.tif")),
            mock.patch.object(core, "CACHE_DIR", Path(tmp)),
            mock.patch.object(core, "OUT_PATH", out_path),
            # The T-M0-3 determinism seams, identical to capture_corrected.py
            # (fixtures/seams.py): the acquisition clock is pinned so the
            # REAL sidecar-to-snapshot acquired flow is exercised; the
            # materialized sha is a fixture-only sentinel so byte-pins never
            # depend on platform GeoTIFF encoder bytes (the real linkage is
            # covered in test_core.py).
            mock.patch.object(core, "_acquisition_stamp", lambda: FIXED_DATE),
            mock.patch.object(core, "materialized_sha256",
                              lambda path: SENTINEL_SHA256),
        ]
        if env is not None:
            patches.append(mock.patch.dict("os.environ", env))
        from scripts.landscape.__main__ import main
        with mock.patch.object(core, "log", lambda msg: None):
            for p in patches:
                p.start()
            try:
                rc = main(argv)
            finally:
                for p in reversed(patches):
                    p.stop()
        return rc, out_path

    def _want_bytes(self) -> bytes:
        return (CORRECTED / "snapshot_terrain_l3.json").read_bytes()

    def test_full_snapshot_matches_corrected_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            rc, out_path = self._run_main(
                tmp, ["--only", "terrain", "--level", "3",
                      "--retrieved", "2026-01-01"])
            self.assertEqual(rc, 0)
            got = out_path.read_bytes()
        self.assertEqual(got, self._want_bytes())

    def test_env_var_pins_retrieved_stamp(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            rc, out_path = self._run_main(
                tmp, ["--only", "terrain", "--level", "3"],
                env={core.RETRIEVED_ENV: "2026-01-01"})
            self.assertEqual(rc, 0)
            got = out_path.read_bytes()
        self.assertEqual(got, self._want_bytes())

    def test_unpinned_stamp_uses_cache_acquisition_date(self) -> None:
        """Without a pin, the snapshot's retrieved stamp must be the cache
        sidecar's acquisition date, not the invocation date, so reusing an
        old materialization can never stamp a false fresh date."""
        with tempfile.TemporaryDirectory() as tmp:
            rc, out_path = self._run_main(
                tmp, ["--only", "terrain", "--level", "3"])
            self.assertEqual(rc, 0)
            sidecars = list(Path(tmp).glob("*.meta.json"))
            self.assertEqual(len(sidecars), 1)
            meta = json.loads(sidecars[0].read_text(encoding="utf-8"))
            meta["acquired"] = "2025-06-30"
            sidecars[0].write_bytes(
                (json.dumps(meta, indent=2) + "\n").encode("utf-8"))
            rc, out_path = self._run_main(
                tmp, ["--only", "terrain", "--level", "3"])
            self.assertEqual(rc, 0)
            snapshot = json.loads(out_path.read_text(encoding="utf-8"))
        self.assertEqual(snapshot["retrieved"], "2025-06-30")
        # The per-source acquired field (schema 1.2.0) carries the SAME
        # sidecar date: acquisition provenance flows from the sidecar, and
        # nothing (not even the reproducibility pin, tested below) rewrites
        # it.
        self.assertEqual(snapshot["sources"]["terrain"]["acquired"],
                         "2025-06-30")

    def test_pin_never_rewrites_acquired(self) -> None:
        """The reproducibility pin governs the TOP-LEVEL retrieved stamp
        only: a pinned run over an older cache must stamp the pin at the
        top level while the per-source acquired field keeps the sidecar's
        real acquisition date (the F1 warm-cache-under-newer-pin case)."""
        with tempfile.TemporaryDirectory() as tmp:
            rc, _ = self._run_main(
                tmp, ["--only", "terrain", "--level", "3"])
            self.assertEqual(rc, 0)
            sidecars = list(Path(tmp).glob("*.meta.json"))
            self.assertEqual(len(sidecars), 1)
            meta = json.loads(sidecars[0].read_text(encoding="utf-8"))
            meta["acquired"] = "2025-06-30"
            sidecars[0].write_bytes(
                (json.dumps(meta, indent=2) + "\n").encode("utf-8"))
            rc, out_path = self._run_main(
                tmp, ["--only", "terrain", "--level", "3",
                      "--retrieved", "2026-02-02"])
            self.assertEqual(rc, 0)
            snapshot = json.loads(out_path.read_text(encoding="utf-8"))
        self.assertEqual(snapshot["retrieved"], "2026-02-02")
        self.assertEqual(snapshot["sources"]["terrain"]["acquired"],
                         "2025-06-30")

    def test_level_both_materializes_once(self) -> None:
        """Once per FAMILY, not once per level: `--level both` must reuse a
        single materialized raster for both zonal sets."""
        gdf3 = load_fixture_gdf()
        gdf4 = gdf3.copy()
        gdf4["US_L4CODE"] = gdf4["US_L3CODE"] + "a"
        gdf4["US_L4NAME"] = gdf4["US_L3NAME"]
        calls: list = []
        real = core.materialize_raster

        def counting(*args, **kwargs):
            calls.append(args)
            return real(*args, **kwargs)

        with tempfile.TemporaryDirectory() as tmp:
            out_path = Path(tmp) / "snapshot.json"
            from scripts.landscape.__main__ import main
            with mock.patch.object(core, "load_ecoregions",
                                   lambda level: gdf3 if level == 3 else gdf4), \
                 mock.patch.object(terrain, "DEM_VRT", str(SYNTH / "dem.tif")), \
                 mock.patch.object(core, "CACHE_DIR", Path(tmp)), \
                 mock.patch.object(core, "OUT_PATH", out_path), \
                 mock.patch.object(core, "materialize_raster", counting), \
                 mock.patch.object(core, "log", lambda msg: None):
                rc = main(["--only", "terrain", "--level", "both",
                           "--retrieved", "2026-01-01"])
            self.assertEqual(rc, 0)
        self.assertEqual(len(calls), 1)


class MainLevelFailureIsOneAttempt(unittest.TestCase):
    def test_union_failure_is_not_retried_per_level(self) -> None:
        """A failed family materialization must be ONE attempt: every level
        reports explicit unavailability without re-materializing."""
        gdf3 = load_fixture_gdf()
        gdf4 = gdf3.copy()
        gdf4["US_L4CODE"] = gdf4["US_L3CODE"] + "a"
        gdf4["US_L4NAME"] = gdf4["US_L3NAME"]
        calls: list = []
        real = core.materialize_raster

        def counting(*args, **kwargs):
            calls.append(args)
            return real(*args, **kwargs)

        with tempfile.TemporaryDirectory() as tmp:
            out_path = Path(tmp) / "snapshot.json"
            from scripts.landscape.__main__ import main
            with mock.patch.object(core, "load_ecoregions",
                                   lambda level: gdf3 if level == 3 else gdf4), \
                 mock.patch.object(terrain, "DEM_VRT",
                                   str(Path(tmp) / "missing.tif")), \
                 mock.patch.object(core, "CACHE_DIR", Path(tmp)), \
                 mock.patch.object(core, "OUT_PATH", out_path), \
                 mock.patch.object(core, "materialize_raster", counting), \
                 mock.patch.object(core, "log", lambda msg: None):
                rc = main(["--only", "terrain", "--level", "both",
                           "--retrieved", "2026-01-01"])
            self.assertEqual(rc, 0)
            snapshot = json.loads(out_path.read_text(encoding="utf-8"))
        self.assertEqual(len(calls), 1)
        for code, entry in snapshot["bundles"].items():
            terrain_block = entry["terrain"]
            self.assertTrue(terrain_block["unavailable"], code)


class MaterializationFailureHonesty(unittest.TestCase):
    def test_failure_reports_explicit_unavailability(self) -> None:
        """A materialization failure must become per-polygon unavailability
        (the legacy explicit-unavailability contract), never an abort."""
        gdf = load_fixture_gdf()
        with tempfile.TemporaryDirectory() as tmp, \
             mock.patch.object(core, "log", lambda msg: None):
            result = terrain.aggregate(
                gdf, "US_L3CODE",
                dem_path=str(Path(tmp) / "does-not-exist.tif"),
                cache_dir=Path(tmp),
            )
        self.assertEqual(result["4"], {"unavailable": True, "reason": "empty geometry"})
        for code in ("1", "2", "3"):
            self.assertTrue(result[code]["unavailable"])
            self.assertIn("dem materialization failed", result[code]["reason"])


if __name__ == "__main__":
    unittest.main()
