/**
 * Generated by scripts/build-minimap-whp.mjs.
 *
 * Compact, approximate area-weighted overview of the official 2023
 * United States Forest Service Wildfire Hazard Potential rasters. This
 * is static strategic context, not current fire conditions or a forecast.
 * Re-run the generator to update; do not hand-edit the values.
 */

import type { FramingKey } from './framings';

export type MinimapWhpCoverage = 'live' | 'live-partial' | 'no-data';

export interface MinimapWhpFramingSummary {
  readonly coverage: MinimapWhpCoverage;
  readonly highOrVeryHighPercent: number | null;
  readonly moderateOrHigherPercent: number | null;
  readonly landSamples: number;
  readonly waterSamplesExcluded: number;
  readonly noDataSamples: number;
}

export interface MinimapWhpArtifact {
  readonly schemaVersion: 1;
  readonly source: Readonly<Record<string, unknown>>;
  readonly method: Readonly<Record<string, unknown>>;
  readonly framings: Readonly<Record<FramingKey, MinimapWhpFramingSummary>>;
}

export const MINIMAP_WHP = {
  "schemaVersion": 1,
  "source": {
    "organization": "United States Forest Service",
    "product": "Wildfire Hazard Potential for the United States",
    "edition": "2023, 4th edition, updated 2024-07-17",
    "doi": "10.2737/RDS-2015-0047-4",
    "service": "https://imagery.geoplatform.gov/iipp/rest/services/Fire_Aviation/USFS_EDW_RMRS_WildfireHazardPotentialClassified/ImageServer",
    "retrievedUtc": "2026-08-10T06:06:40.385Z",
    "rasterMembers": {
      "1": "whp2023_cls_hi",
      "2": "whp2023_cls_ak",
      "3": "whp2023_cls_conus"
    },
    "landscapeConditions": "end of 2020"
  },
  "method": {
    "approximate": true,
    "outputCrs": "EPSG:4326",
    "interpolation": "nearest neighbor",
    "mainlandStepDegrees": 0.05,
    "hawaiiStepDegrees": 0.01,
    "areaWeight": "cosine of pixel-center latitude",
    "denominator": "classes 1 through 6; class 7 water excluded",
    "thresholds": {
      "highOrVeryHighPercent": "strictly greater than 50",
      "moderateOrHigherPercent": "strictly greater than 30"
    },
    // vocab-allow: honesty disclaimer denying that static WHP is a forecast
    "qualification": "Static strategic potential overview, not current fire conditions or a forecast.",
    "palette": {
      "1": {
        "label": "Very Low",
        "rgba": [
          56,
          163,
          0,
          255
        ]
      },
      "2": {
        "label": "Low",
        "rgba": [
          163,
          255,
          148,
          255
        ]
      },
      "3": {
        "label": "Moderate",
        "rgba": [
          255,
          255,
          99,
          255
        ]
      },
      "4": {
        "label": "High",
        "rgba": [
          255,
          163,
          0,
          255
        ]
      },
      "5": {
        "label": "Very High",
        "rgba": [
          237,
          30,
          0,
          255
        ]
      },
      "6": {
        "label": "Non-burnable",
        "rgba": [
          225,
          225,
          225,
          255
        ]
      },
      "7": {
        "label": "Water",
        "rgba": [
          0,
          112,
          225,
          255
        ]
      }
    }
  },
  "framings": {
    "alaska-northwest": {
      "coverage": "live-partial",
      "highOrVeryHighPercent": 10.059,
      "moderateOrHigherPercent": 21.727,
      "landSamples": 106017,
      "waterSamplesExcluded": 14293,
      "noDataSamples": 406199
    },
    "boreal-arctic": {
      "coverage": "no-data",
      "highOrVeryHighPercent": null,
      "moderateOrHigherPercent": null,
      "landSamples": 0,
      "waterSamplesExcluded": 0,
      "noDataSamples": 0
    },
    "pacific-coast": {
      "coverage": "live-partial",
      "highOrVeryHighPercent": 33.194,
      "moderateOrHigherPercent": 60.432,
      "landSamples": 33682,
      "waterSamplesExcluded": 974,
      "noDataSamples": 34839
    },
    "arid-west": {
      "coverage": "live",
      "highOrVeryHighPercent": 19.692,
      "moderateOrHigherPercent": 35.039,
      "landSamples": 73139,
      "waterSamplesExcluded": 965,
      "noDataSamples": 398
    },
    "plains-prairies": {
      "coverage": "live-partial",
      "highOrVeryHighPercent": 5.496,
      "moderateOrHigherPercent": 14.898,
      "landSamples": 93090,
      "waterSamplesExcluded": 1395,
      "noDataSamples": 34380
    },
    "eastern-forests": {
      "coverage": "live-partial",
      "highOrVeryHighPercent": 2.213,
      "moderateOrHigherPercent": 10.76,
      "landSamples": 49421,
      "waterSamplesExcluded": 9557,
      "noDataSamples": 69855
    },
    "southeast-gulf": {
      "coverage": "live",
      "highOrVeryHighPercent": 13.077,
      "moderateOrHigherPercent": 32.145,
      "landSamples": 71339,
      "waterSamplesExcluded": 4457,
      "noDataSamples": 1058
    },
    "mexico": {
      "coverage": "no-data",
      "highOrVeryHighPercent": null,
      "moderateOrHigherPercent": null,
      "landSamples": 0,
      "waterSamplesExcluded": 0,
      "noDataSamples": 0
    },
    "hawaii": {
      "coverage": "live",
      "highOrVeryHighPercent": 5.576,
      "moderateOrHigherPercent": 17.919,
      "landSamples": 11975,
      "waterSamplesExcluded": 3289,
      "noDataSamples": 2705
    }
  }
} as const satisfies MinimapWhpArtifact;
