/**
 * Honest-links check: verify that every literal https:// URL the module
 * ships (cataloged resources, endpoint roots, popup link-outs, claim source
 * links) still responds.
 *
 * The module's sourcing doctrine is "strongly verified": every endpoint and
 * resource link is live-checked before it enters the codebase, with a dated
 * verification stamp. Verification decays silently as agencies reorganize
 * their sites; this script re-checks the links so decay surfaces as a
 * scheduled-workflow failure (and an issue) instead of a broken link a user
 * discovers during a drought emergency.
 *
 * Scope: literal URLs in the scanned source files. Templated URLs (query
 * parameters filled at runtime, tile templates) are skipped; the endpoint
 * ROOT of each templated service is usually also present as a literal and is
 * checked. URLs generated by code (for example the drought.gov state pages
 * built by `droughtGovStateUrl`) are represented by their verified pattern
 * samples below.
 *
 * Usage: node scripts/check-links.mjs
 * Exit code 0 when every check passes; 1 when any link fails.
 */

import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const FILES = [
  'src/config/urls.ts',
  'src/impact/resources.ts',
  'src/impact/sources.ts',
  'src/impact/hydrate.ts',
  'src/impact/enso.ts',
  'src/ui/popups.ts'
];

/**
 * Pattern samples for code-generated URL families. Each stands in for the
 * whole family; if the pattern breaks, the generator needs re-verification.
 */
const GENERATED_SAMPLES = [
  // droughtGovStateUrl: hyphenated-name slug pattern (spot-verified 2026-07-01).
  'https://www.drought.gov/states/texas',
  'https://www.drought.gov/states/new-mexico',
  'https://www.drought.gov/states/washington'
];

const TIMEOUT_MS = 20_000;
const CONCURRENCY = 5;
const USER_AGENT =
  'DDM-link-check/1.0 (+https://github.com/atniclimate/dynamic-drought-module)';

/** Extract literal https URLs from source text, skipping templates. */
function extractUrls(text) {
  const found = new Set();
  const re = /https:\/\/[^\s'"`<>)\]}]+/g;
  for (const match of text.matchAll(re)) {
    let url = match[0];
    // Trim trailing punctuation that rode along from prose or markup.
    url = url.replace(/[.,;:!?]+$/, '');
    // Skip runtime templates and interpolations.
    if (url.includes('${') || url.includes('{bbox')) continue;
    found.add(url);
  }
  return found;
}

/** GET a URL with a timeout; any status below 400 passes. */
async function checkUrl(url) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: 'GET',
      redirect: 'follow',
      signal: ctrl.signal,
      headers: { 'User-Agent': USER_AGENT }
    });
    return { url, ok: res.status < 400, status: res.status };
  } catch (err) {
    return { url, ok: false, status: String(err?.name ?? err) };
  } finally {
    clearTimeout(timer);
  }
}

async function main() {
  const urls = new Set(GENERATED_SAMPLES);
  for (const rel of FILES) {
    const path = fileURLToPath(new URL(`../${rel}`, import.meta.url));
    const text = await readFile(path, 'utf8');
    for (const url of extractUrls(text)) urls.add(url);
  }

  const list = [...urls].sort();
  console.log(`checking ${list.length} links ...\n`);

  const results = [];
  for (let i = 0; i < list.length; i += CONCURRENCY) {
    const batch = list.slice(i, i + CONCURRENCY);
    results.push(...(await Promise.all(batch.map(checkUrl))));
  }

  const failures = results.filter((r) => !r.ok);
  for (const r of results) {
    console.log(`${r.ok ? 'ok  ' : 'FAIL'}  ${String(r.status).padEnd(12)} ${r.url}`);
  }

  console.log(`\n${results.length - failures.length}/${results.length} links healthy`);
  if (failures.length > 0) {
    console.error(`\n${failures.length} link(s) failed; each needs re-verification or replacement:`);
    for (const f of failures) console.error(`  ${f.status}  ${f.url}`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
